Repository loophp/collection, pull requests merged in 2021-12, with the labels that each got.

#226 Fix intersperse operation.
  spec/loophp/collection/CollectionSpec.php
  src/Operation/Intersperse.php
Labels: bug

#228 Use `loophp/iterators`
  composer.json
  spec/loophp/collection/CollectionSpec.php
  spec/loophp/collection/Iterator/ArrayCacheIteratorSpec.php
  spec/loophp/collection/Iterator/ClosureIteratorSpec.php
  spec/loophp/collection/Iterator/IterableIteratorSpec.php
  spec/loophp/collection/Iterator/MultipleIterableIteratorSpec.php
  spec/loophp/collection/Iterator/PsrCacheIteratorSpec.php
  spec/loophp/collection/Iterator/RandomIteratorSpec.php
  spec/loophp/collection/Iterator/ResourceIteratorSpec.php
  spec/loophp/collection/Iterator/StringIteratorSpec.php
  src/Collection.php
  src/Iterator/ArrayCacheIterator.php
  src/Iterator/ClosureIterator.php
  src/Iterator/IterableIterator.php
  src/Iterator/MultipleIterableIterator.php
  src/Iterator/ProxyIterator.php
  src/Iterator/PsrCacheIterator.php
  src/Iterator/RandomIterator.php
  src/Iterator/ResourceIterator.php
  src/Iterator/StringIterator.php
  src/Iterator/TypedIterator.php
  src/Operation/Flatten.php
  src/Operation/Pack.php
  src/Operation/Product.php
  src/Operation/Transpose.php
  src/Operation/Unpack.php
  src/Operation/Zip.php
Labels: enhancement

#229 Simplify operations that needs more than one instance of the `Generator` - using `IteratorAggregate`.
  phpstan-baseline.neon
  src/Collection.php
  src/Operation/Partition.php
  src/Operation/Span.php
Labels: enhancement

#230 Refactor: Replace `RandomIterator`
  composer.json
  spec/loophp/collection/CollectionSpec.php
  spec/loophp/collection/Iterator/RandomIteratorSpec.php
  src/Collection.php
  src/Iterator/RandomIterator.php
  src/Operation/Shuffle.php
Labels: enhancement

#227 Tests: Switch to PHPUnit
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/settings.yml
  .github/workflows/code-style.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  .gitignore
  .php-cs-fixer.dist.php
  .scrutinizer.yml
  README.md
  composer.json
  docs/pages/principles.rst
  docs/pages/tests.rst
  grumphp.yml
  infection.json
  phpspec.yml
  phpunit.xml
  psalm.xml
  spec/loophp/collection/CollectionSpec.php
  spec/loophp/collection/Iterator/MultipleIterableIteratorSpec.php
  spec/loophp/collection/Iterator/ResourceIteratorSpec.php
  spec/loophp/collection/Iterator/StringIteratorSpec.php
  spec/loophp/collection/Iterator/TypedIteratorSpec.php
  spec/loophp/collection/Operation/CoalesceSpec.php
  spec/loophp/collection/Operation/CurrentSpec.php
  spec/loophp/collection/Operation/LimitSpec.php
  spec/loophp/collection/Utils/CallbacksArrayReducerSpec.php
  tests/fixtures/sample.txt
  tests/unit/CollectionConstructorsTest.php
  tests/unit/CollectionGenericOperationTest.php
  tests/unit/CollectionSpecificOperationTest.php
  tests/unit/Iterator/MultipleIterableIteratorTest.php
  tests/unit/Iterator/PsrCacheIteratorTest.php
  tests/unit/Iterator/ResourceIteratorTest.php
  tests/unit/Iterator/StringIteratorTest.php
  tests/unit/Iterator/TypedIteratorTest.php
  tests/unit/Traits/GenericCollectionProviders.php
  tests/unit/Utils/CallbacksArrayReducerTest.php
Labels: dependencies
