Repository loophp/collection, pull requests merged in 2021-07, with the labels that each got.

#115 feat: Add Matching operation and implements Selectable from Doctrine.
  composer.json
  docs/pages/api.rst
  docs/pages/code/operations/matching.php
  spec/loophp/collection/CollectionSpec.php
  src/Collection.php
  src/Contract/Collection.php
  src/Contract/Operation/Matchingable.php
  src/Operation/Matching.php
  tests/static-analysis/matching.php
Labels: enhancement

#126 Update `Filter` operation.
  docs/pages/api.rst
  docs/pages/code/operations/filter.php
  spec/loophp/collection/CollectionSpec.php
  src/Operation/Filter.php
Labels: enhancement

#124 Refactor `::partition()` and `::span()`
  docs/pages/api.rst
  docs/pages/code/operations/partition.php
  docs/pages/code/operations/span.php
  spec/loophp/collection/CollectionSpec.php
  src/Collection.php
  src/Contract/Operation/Partitionable.php
  src/Contract/Operation/Spanable.php
  src/Operation/Partition.php
  src/Operation/Span.php
  tests/static-analysis/partition.php
  tests/static-analysis/span.php
Labels: enhancement

#131 Provide util class for reducer callback
  spec/loophp/collection/Utils/CallbacksArrayReducerSpec.php
  src/Operation/DropWhile.php
  src/Operation/Every.php
  src/Operation/Filter.php
  src/Operation/MatchOne.php
  src/Operation/Reject.php
  src/Operation/Since.php
  src/Operation/Split.php
  src/Operation/TakeWhile.php
  src/Operation/Until.php
  src/Utils/CallbacksArrayReducer.php
Labels: enhancement

#132 Refactor Scalar Operations
  README.md
  docs/index.rst
  docs/pages/api.rst
  docs/pages/code/operations/background.php
  docs/pages/code/operations/match.php
  docs/pages/installation.rst
  docs/pages/requirements.rst
  spec/loophp/collection/CollectionSpec.php
  src/Collection.php
  src/Contract/Collection.php
  src/Contract/Operation/Containsable.php
  src/Contract/Operation/Everyable.php
  src/Contract/Operation/Falsyable.php
  src/Contract/Operation/Hasable.php
  src/Contract/Operation/Matchable.php
  src/Contract/Operation/Nullsyable.php
  src/Contract/Operation/Truthyable.php
  src/Operation/Falsy.php
  src/Operation/MatchOne.php
  src/Operation/Nullsy.php
  src/Operation/Truthy.php
  src/Utils/CallbacksArrayReducer.php
  tests/static-analysis/contains.php
  tests/static-analysis/every.php
  tests/static-analysis/falsy.php
  tests/static-analysis/has.php
  tests/static-analysis/match.php
  tests/static-analysis/nullsy.php
  tests/static-analysis/truthy.php
Labels: backward breaking change, enhancement

#138 Update `Reverse` operation - optimize and remove todos.
  src/Operation/Reverse.php
  tests/static-analysis/reverse.php
Labels: enhancement

#145 refactor: Rename variables and properties.
  spec/loophp/collection/Iterator/TypedIteratorSpec.php
  src/Iterator/ClosureIterator.php
  src/Iterator/TypedIterator.php
  src/Operation/Associate.php
  src/Operation/Transpose.php
Labels: backward breaking change, enhancement

#146 refactor: Reduce the use of the spread operators and variadic parameters
  spec/loophp/collection/CollectionSpec.php
  spec/loophp/collection/Iterator/ClosureIteratorSpec.php
  src/Collection.php
  src/Iterator/ClosureIterator.php
  src/Iterator/IterableIterator.php
  src/Iterator/TypedIterator.php
  tests/static-analysis/fromCallable.php
Labels: backward breaking change, enhancement

#148 Update Span and Partition operations.
  docs/pages/api.rst
  spec/loophp/collection/CollectionSpec.php
  src/Collection.php
  src/Operation/Partition.php
  src/Operation/Span.php
Labels: bug

#154 Fix: Prevent warning when using odd amount of items.
  spec/loophp/collection/CollectionSpec.php
  src/Operation/Pair.php
Labels: bug

#157 `Drop` accepts non-variadic `count`
  docs/pages/api.rst
  spec/loophp/collection/CollectionSpec.php
  src/Collection.php
  src/Contract/Operation/Dropable.php
  src/Operation/Drop.php
  tests/static-analysis/drop.php
Labels: backward breaking change

#161 Temporary workaround until phpstan/phpstan#5372 is fixed.
  phpstan-unsupported-baseline.neon
Labels: bug

#150 feat: Add `::fromGenerator` constructor.
  docs/pages/api.rst
  spec/loophp/collection/CollectionSpec.php
  src/Collection.php
  tests/static-analysis/fromGenerator.php
Labels: new feature

#153 Improve static analysis tests
  phpstan-unsupported-baseline.neon
  src/Contract/Operation/Linesable.php
  src/Contract/Operation/Pairable.php
  src/Contract/Operation/Reduceable.php
  src/Contract/Operation/Reductionable.php
  src/Contract/Operation/ScanLeft1able.php
  src/Contract/Operation/ScanLeftable.php
  src/Contract/Operation/ScanRight1able.php
  src/Contract/Operation/ScanRightable.php
  src/Contract/Operation/Windowable.php
  src/Operation/Lines.php
  src/Operation/Pair.php
  src/Operation/Pipe.php
  src/Operation/Reduce.php
  src/Operation/Reduction.php
  src/Operation/ScanLeft.php
  src/Operation/ScanLeft1.php
  src/Operation/ScanRight.php
  src/Operation/ScanRight1.php
  tests/static-analysis/asyncMap.php
  tests/static-analysis/asyncMapN.php
  tests/static-analysis/flatMap.php
  tests/static-analysis/lines.php
  tests/static-analysis/map.php
  tests/static-analysis/pack.php
  tests/static-analysis/pair.php
  tests/static-analysis/reduce.php
  tests/static-analysis/reduction.php
  tests/static-analysis/scanLeft.php
  tests/static-analysis/scanLeft1.php
  tests/static-analysis/scanRight.php
  tests/static-analysis/scanRight1.php
  tests/static-analysis/tail.php
  tests/static-analysis/tails.php
  tests/static-analysis/window.php
Labels: enhancement

#163 refactor: Make constructor private.
  src/Collection.php
Labels: backward breaking change, enhancement

#165 SA: Update operations.
  src/Collection.php
  src/Operation/Partition.php
  src/Operation/Span.php
  src/Operation/Transpose.php
  src/Operation/Unpair.php
  tests/static-analysis/scanLeft.php
  tests/static-analysis/scanRight.php
Labels: enhancement
